/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Teacher;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2022-11-14T16:01:06.666Z[GMT]")
@Validated
public interface TeacherApi {

    @Operation(summary = "Add a new teacher to the list", description = "Add a new teacher to the list", security = {
        @SecurityRequirement(name = "schoolResources_auth", scopes = {
            "write:students",
"read:students",
"write:teachers",
"read:teachers",
"write:schools",
"read:schools"        })    }, tags={ "teacher" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Teacher.class))),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/teacher",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        method = RequestMethod.POST)
    ResponseEntity<Teacher> addTeacher(@Parameter(in = ParameterIn.DEFAULT, description = "Create a new teacher in the school", required=true, schema=@Schema()) @Valid @RequestBody Teacher body);


    @Operation(summary = "Deletes a Teacher", description = "delete a Teacher", security = {
        @SecurityRequirement(name = "schoolResources_auth", scopes = {
            "write:students",
"read:students",
"write:teachers",
"read:teachers",
"write:schools",
"read:schools"        })    }, tags={ "teacher" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid pet value") })
    @RequestMapping(value = "/teacher/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTeacher(@Parameter(in = ParameterIn.PATH, description = "Teacher id to delete", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Deletes all teacher", description = "delete all teacher", security = {
        @SecurityRequirement(name = "schoolResources_auth", scopes = {
            "write:students",
"read:students",
"write:teachers",
"read:teachers",
"write:schools",
"read:schools"        })    }, tags={ "teacher" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid pet value") })
    @RequestMapping(value = "/teacher",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteTeachers();


    @Operation(summary = "Find Teacher by ID", description = "Returns a single Teacher", security = {
        @SecurityRequirement(name = "api_key"),
@SecurityRequirement(name = "schoolResources_auth", scopes = {
            "write:students",
"read:students",
"write:teachers",
"read:teachers",
"write:schools",
"read:schools"        })    }, tags={ "teacher" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Teacher.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Teacher not found") })
    @RequestMapping(value = "/teacher/{id}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Teacher> getTeacherById(@Parameter(in = ParameterIn.PATH, description = "ID of Teacher to return", required=true, schema=@Schema()) @PathVariable("id") Long id);


    @Operation(summary = "Returns the list with all teachers", description = "Returns the list with all teachers", security = {
        @SecurityRequirement(name = "schoolResources_auth", scopes = {
            "write:students",
"read:students",
"write:teachers",
"read:teachers",
"write:schools",
"read:schools"        })    }, tags={ "teacher" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Teacher.class))),
        
        @ApiResponse(responseCode = "404", description = "Teachers not found") })
    @RequestMapping(value = "/teacher",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Teacher> returnAllTeachers();


    @Operation(summary = "Updates a Teacher", description = "", security = {
        @SecurityRequirement(name = "schoolResources_auth", scopes = {
            "write:students",
"read:students",
"write:teachers",
"read:teachers",
"write:schools",
"read:schools"        })    }, tags={ "teacher" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Teacher.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/teacher/{id}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Teacher> updateTeacherWithForm(@Parameter(in = ParameterIn.PATH, description = "ID of Teacher that needs to be updated", required=true, schema=@Schema()) @PathVariable("id") Long id);

}

